server:
  port: 9500

  servlet:
    context-path: /pk-sparkweb

spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: root
    url: jdbc:mysql://hadoop000:3306/pk
    driver-class-name: com.mysql.jdbc.Driver    #NEED TO ADD DEPENDENCY
  redis:
    host: hadoop000
    port: 6379
    database: 0
hbase:
  zookeeper:
    quorum: hadoop000
    property:
      clientPort: 2181



zookeeper:
  znode:
    parent: /hbase